baseURL = "http://gonzalezandrew.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "Andrew Gonzalez"
title = "Andrew Gonzalez"
theme = "hugo-vitae"
paginate = 5
enableRobotsTXT = true

copyright = "© Andrew Gonzalez 2020 - 2021. Powerd by [Hugo](https://gohugo.io)"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses=true

googleAnalytics = ""

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
	# Use homepage.md instead of a list of posts
	homepage = false

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = ["hugo","aws","python","sql"]

	# Add meta description in head part
	description = "Recent content by Andrew Gonzalez."

	# Add pagetitle to homepage <title> tag
	pagetitle = "Andrew Gonzalez"

	# Add a subtitle to your website
	subtitle = "Head in the clouds."

	# Activate to show authors on pages if available
	#listAuthor = true

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Optional 80x80 avatar image.
	avatar = "/images/me.jpg"

	# Optional favicons for website
	#favicon = true

	# Add list of sections that should show up on the homepage
        mainSections = ["posts"]

	# Add list of Sections/Types that should no be considered by RSS
	#nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Custom CSS applied to default styles. (Path could be "static/css/")
	#customCSS = "css/syntax.css"

# Comments
[params.comments]
# Enable Comments with "true"
enabled = false

# Comment provider:
#   disqus (https://disqus.com)
#   commento (https://commento.io)
#engine = "disqus"

# Content types to disable comments on.
#disableOnTypes = ["page"]

[params.comments.disqus]
#shortname = "" # Paste the shortname from your Disqus dashboard.

[params.comments.commento]
#host = "" # Paste the domain of you commento.io system

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

# [[menu.main]]
# name = "Categories"
# url = "/categories"
# weight = 5

# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/GonzalezAndrew"

[[params.social]]
name = "Twitter"
icon = "fab fa-twitter-square"
url = "https://twitter.com/_GonzalezAndrew"

[[params.social]]
name = "LinkedIn"
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/-andrew-gonzalez/"

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
noClasses = true  